# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/leonard/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/osm_2_imm/ui/osm_2_imm_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDialogBase(object):
    def setupUi(self, MainDialogBase):
        MainDialogBase.setObjectName("MainDialogBase")
        MainDialogBase.resize(367, 390)
        self.button_box = QtWidgets.QDialogButtonBox(MainDialogBase)
        self.button_box.setGeometry(QtCore.QRect(50, 340, 291, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayoutWidget = QtWidgets.QWidget(MainDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 297, 280))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_layer = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_layer.setChecked(True)
        self.rb_layer.setObjectName("rb_layer")
        self.verticalLayout.addWidget(self.rb_layer)
        self.layer = gui.QgsMapLayerComboBox(self.verticalLayoutWidget)
        self.layer.setProperty("showCrs", True)
        self.layer.setObjectName("layer")
        self.verticalLayout.addWidget(self.layer)
        self.rb_limits = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_limits.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.rb_limits.setChecked(False)
        self.rb_limits.setObjectName("rb_limits")
        self.verticalLayout.addWidget(self.rb_limits)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.south = gui.QgsFilterLineEdit(self.verticalLayoutWidget)
        self.south.setProperty("qgisRelation", "")
        self.south.setObjectName("south")
        self.horizontalLayout_3.addWidget(self.south)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.north = gui.QgsFilterLineEdit(self.verticalLayoutWidget)
        self.north.setProperty("qgisRelation", "")
        self.north.setObjectName("north")
        self.horizontalLayout_2.addWidget(self.north)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.east = gui.QgsFilterLineEdit(self.verticalLayoutWidget)
        self.east.setProperty("qgisRelation", "")
        self.east.setObjectName("east")
        self.horizontalLayout_5.addWidget(self.east)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.west = gui.QgsFilterLineEdit(self.verticalLayoutWidget)
        self.west.setProperty("qgisRelation", "")
        self.west.setObjectName("west")
        self.horizontalLayout_4.addWidget(self.west)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.outputLoc = gui.QgsFileWidget(self.verticalLayoutWidget)
        self.outputLoc.setObjectName("outputLoc")
        self.verticalLayout.addWidget(self.outputLoc)

        self.retranslateUi(MainDialogBase)
        self.button_box.accepted.connect(MainDialogBase.accept)
        self.button_box.rejected.connect(MainDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(MainDialogBase)

    def retranslateUi(self, MainDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MainDialogBase.setWindowTitle(_translate("MainDialogBase", "OSM to IMM"))
        self.rb_layer.setText(_translate("MainDialogBase", "Bounding box from layer:"))
        self.rb_limits.setText(_translate("MainDialogBase", "Input bounding box limits (WGS 84 lon/lat):"))
        self.label_2.setText(_translate("MainDialogBase", "South:"))
        self.south.setPlaceholderText(_translate("MainDialogBase", "South bounds (lat)"))
        self.label.setText(_translate("MainDialogBase", "North:"))
        self.north.setPlaceholderText(_translate("MainDialogBase", "North bounds (lat)"))
        self.label_4.setText(_translate("MainDialogBase", "East:"))
        self.east.setPlaceholderText(_translate("MainDialogBase", "East bounds (lon)"))
        self.label_3.setText(_translate("MainDialogBase", "West:"))
        self.west.setPlaceholderText(_translate("MainDialogBase", "West bounds (lon)"))
        self.label_5.setText(_translate("MainDialogBase", "Output location: "))
from qgis import gui
