# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Core
                                 A QGIS plugin
 This plugin loads data from OSM in layers suitable for IMM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-08
        copyright            : (C) 2022 by Leonard Hökby
        email                : bing.hawk@telia.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This package contain all files working with Overpy and the business logic
 of the plugin such as queries, parsing and a wrapper function to run it.
 """

__author__ = 'bing.hawk@telia.com'
__date__ = '2022-07-08'
__copyright__ = 'Copyright 2022, Leonard Hökby'